### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by ghost** [SparkPost/nodemailer-sparkpost-transport#18]
Does this support templates, and if so how can I pass data into the template?

**Comment by mautematico** [comment]
I have that same question. I think it **is** able to use templates, see unit tests:

template_id:
https://github.com/SparkPost/nodemailer-sparkpost-transport/blob/master/test/sparkpostTransport.js#L32

substitution_data:
https://github.com/SparkPost/nodemailer-sparkpost-transport/blob/master/test/sparkpostTransport.js#L30
