### ISSUE TITLE
anything we had to fix to use the europe endpoint?

### ISSUE THREAD

**Issue by luisrudge** [SparkPost/nodemailer-sparkpost-transport#20]
when using the API key, do we need to set which API we want to hit (eu vs us)?

**Comment by luisrudge** [comment]
ping @aydrian

**Comment by aydrian** [comment]
Hello. I no longer maintain this library. @avigoldman or @jgzamora can assist you.

**Comment by luisrudge** [comment]
@aydrian sorry to ping you (I looked at the last commits).

**Comment by luisrudge** [comment]
ping @avigoldman @jgzamora

**Comment by avigoldman** [comment]
Hey @luisrudge 👋 looks like this library doesn't have support for EU yet. I'll get started on a PR for it right now.

**Comment by avigoldman** [comment]
@luisrudge I've got the [PR](https://github.com/SparkPost/nodemailer-sparkpost-transport/pull/21) ready. Once it is reviewed, I'll cut a new release.

**Comment by avigoldman** [comment]
@luisrudge upgrade to `v2.1.0` and set the [`endpoint`](https://github.com/SparkPost/nodemailer-sparkpost-transport#create-a-nodemailer-transport-object) to `https://api.eu.sparkpost.com` to use your SparkPost EU account.

**Comment by luisrudge** [comment]
Thanks @avigoldman!
