### ISSUE TITLE
Add cc/bcc support

### ISSUE THREAD

**Issue by colestrode** [SparkPost/nodemailer-sparkpost-transport#8]
Support cc/bcc options nodemailer options

**Comment by amesas** [comment]
Missing basic features.

Is it documented anywhere those missing features?

It should be documented and bold :O

**Comment by ewandennis** [comment]
@amesas CC and BCC supported were added in the latest release: 2.0.0.

**Comment by iamchathu** [comment]
bcc still doesn't work @ewandennis
