### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by colestrode** [SparkPost/nodemailer-sparkpost-transport#9]
Add attachment support from the common nodemailer options: https://github.com/nodemailer/nodemailer#e-mail-message-fields

**Comment by cameronk** [comment]
Looking forward to seeing this feature.

**Comment by amesas** [comment]
Any news on this?

**Comment by JuicyBB** [comment]
Does this support attachments now ?

**Comment by aazcast** [comment]
This is implemented?

**Comment by jgzamora** [comment]
👋 Hi all, sorry for the delay on this. I submitted #22 to add support. It also add support for mapping the Nodemailer fields `headers` & `replyTo` to their SparkPost counterparts. As a side note, attachments and other features are possible by using the SparkPost specific fields, like `content`.

**Comment by jgzamora** [comment]
Version `2.2.0` with attachment support has been published on npm.
